language: android
script:
- git fetch origin --tags
- "./gradlew assembleRelease"
git:
  submodules: true
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_26e1bb6b6b4a_key -iv $encrypted_26e1bb6b6b4a_iv
  -in keystore.tar.enc -out keystore.tar -d
- tar xvf keystore.tar
- export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin
install:
- echo y | sdkmanager 'ndk-bundle'
- echo y | sdkmanager 'cmake;3.6.4111459'
- echo y | sdkmanager 'platform-tools'
- echo y | sdkmanager 'build-tools;28.0.3'
- echo y | sdkmanager 'platforms;android-28'
before_deploy:
- export DATE=$(date +%Y%m%d)
- export SHA256=$(sha256sum app/build/outputs/apk/release/app-release.apk)
- mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/trime-$DATE-test.apk
- |
   cat > app/build/outputs/apk/README.md <<EOF
   # 同文最新測試版
   **文件名：** [trime-$DATE-test.apk 點擊下載](release/trime-$DATE-test.apk)
   **SHA256：** $SHA256
   **版本：** [$(git describe --tags)-$DATE](https://github.com/osfans/trime/commits/$(git rev-parse HEAD))
   **RIME版本：** [$(git --git-dir=app/src/main/jni/librime/.git describe --tags)](https://github.com/rime/librime/commits/$(git --git-dir=app/src/main/jni/librime/.git rev-parse HEAD))
   **OpenCC版本：** [$(git --git-dir=app/src/main/jni/OpenCC/.git describe --tags)](https://github.com/BYVoid/OpenCC/commits/$(git --git-dir=app/src/main/jni/OpenCC/.git rev-parse HEAD))
   **類型：** 測試版
   **更新於：** $(date +%Y年%m月%d日)

   ## 更新內容
   $(git log $(git describe --tags HEAD^ --abbrev=0).. --format="* %s [%h](https://github.com/osfans/trime/commit/%H)"|sort -r)
   EOF
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: false
  local-dir: app/build/outputs/apk/
  on:
    branch: develop
env:
  global:
  - secure: 44HmwFFIKEmqnAOemuh8mIIbvglb3CZN+I+GsN7CGWn5Pvocg2sULj7sv33NDL6+5012bt3RoT9YgoTf2ERNR2W0bMVYw/0O5qdAnPiLD/v3SaoDv7qW3G9snKPBhdK72eODVxys66EY0oloJiBKQ/QnDr+HUiGpUuZlOaVLXBN9rcNlinM+4nMMSmaEOInhCwYrNI+NwOhoBVx+YNgaSqWBzHNYO7P2iWZfHbh9LmavpVynzp2gQp3VwoX9VrCrnfjLdRy+F0/TsWjiQ/PIbRJo2/Kl8SY93ve1SUfoJoLVTatX9ZG3a2+955+1SKBElI0mlKoMHDj0yy0F9zwUJY0rhbXnjp1EFyFgnRhCiaOKtXQp2+CKjig6V2kXRzxGzXKJ6aEZi8I3I6LKMgasXDgJgyzWmZjI30zBjA/lbWvmlLOkJswxFvQn972hPvhaE3P40OELrEu5uZiCJItkb4rWD2CPMkdz6R5mqbLa6Zn8RthfUyYuD8jh24lasp0wo9a3ARAhaZZnrxIS2p4QFugXzjsp28u4fA8pQDcKcHEZU0/fgun6gKKKkgq/DiIlheWiVO5Y7cnIiSKMYYkqlxiKpP2EbY5nE7yKwXANC+lvNQVBlk1mTP6POD5qeyAj75SeVc52VLAmvvVMKWZHD29KWW3f7JmIOTgrXHcSSck=
